# Generated by Django 4.2.4 on 2023-10-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Melhikapp', '0005_customuser_telegram_chat_id_alter_employer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
            ],
        ),
    ]
